<a href="https://colab.research.google.com/github/paulalopez4/Entreglables_2/blob/master/Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
## Numpy

import numpy as np

#1 Crear un arreglo

#1.1 Desde listas
arr = np.array([100,150,200,250])

print("Desde listas")
print(arr)
print("\n")


#1.2 Desde matrices
mat = np.array([[33,48,25],[11,22,44]])

print("Desde matrices")
print(mat)
print("\n")


#1.3 Con rangos
range = np.arange (2,22,4)

print("Con rangos")
print(range)
print("\n")


#1.4 Arreglo con ceros y unos
zeros = np.zeros ((4,4))
ones = np.ones ((5,3))

print("Arreglo con ceros y unos")
print(zeros)
print(ones)
print("\n")


#1.5 Aleatorios
random = np.random.rand (2,2)
random_int = np.random.randint(2, 111, (2,2))

print("Aleatorios")
print(random)
print(random_int)
print("\n")

Desde listas
[100 150 200 250]


Desde matrices
[[33 48 25]
 [11 22 44]]


Con rangos
[ 2  6 10 14 18]


Arreglo con ceros y unos
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]
 [1. 1. 1.]]


Aleatorios
[[3.81671497e-04 3.36997154e-01]
 [3.40990057e-01 6.35373492e-01]]
[[ 59 100]
 [ 19  30]]




In [ ]:
#2 Propiedades de un arreglo

#2.1 Número de dimensiones
ndim = mat.ndim
print("Número de dimensiones")
print(arr.ndim)
print(mat.ndim)
print("\n")

#2.2 Forma
shape = mat.shape
print("Forma")
print(arr.shape)
print(mat.shape)
print("\n")

#2.3 Número de elementos
size = mat.size
print("Tamaño")
print(arr.size)
print(mat.size)
print("\n")

#2.4 Tipo de dato
dtype = mat.dtype
print("Tipo de dato")
print(dtype)
print("\n")




Número de dimensiones
1
2


Forma
(4,)
(2, 3)


Tamaño
4
6


Tipo de dato
int64




In [ ]:
#3 Indexación y slicing

#3.1 Arreglo
arr2 = np.array([125,150,175,200,225,250])
index = arr2[4]
index_range = arr2[0:5]
slicing = arr2[::1]

print("Índice: ")
print(index)
print("\n")
print("Índice con rango: ")
print(index_range)
print("\n")
print("Slicing: ")
print(slicing)
print("\n")


#3.2 Matrices
mat2 = np.array([[3,7,9],[11,13,19],[23,29,31]])
index2 = mat2[1,2]
index_column = mat2[:,1]
index_row = mat2[2,:]
submatriz = mat2[0:3,1:4]

print("Matriz: ")
print(mat2)
print("\n")
print("índice: ")
print(index2)
print("índice columna: ")
print(index_column)
print("índice fila: ")
print(index_row)
print("\n")
print("Submatriz: ")
print(submatriz)


Índice: 
225


Índice con rango: 
[125 150 175 200 225]


Slicing: 
[125 150 175 200 225 250]


Matriz: 
[[ 3  7  9]
 [11 13 19]
 [23 29 31]]


índice: 
19
índice columna: 
[ 7 13 29]
índice fila: 
[23 29 31]


Submatriz: 
[[ 7  9]
 [13 19]
 [29 31]]


In [ ]:
#4 Operaciones matemáticas

#Suma
suma = arr + 7
print("Suma: ")
print(suma)
print("\n")

#Multiplicación
mult = arr * 14
print("Multiplicación: ")
print(mult)
print("\n")

#División
div = arr / 5
print("División: ")
print(div)
print("\n")

#Potenciación
exp = arr ** 9
print("Exponente: ")
print(exp)
print("\n")


#4.1 Operaciones entre arreglos
a = np.array([444,563,313])
b = np.array([674,555,808])

sum_arr = a + b
mult_arr = a * b
div_arr = a / b
exp_arr = a ** b

print("Suma de arreglos: ")
print(sum_arr)
print("\n")
print("Multiplicación de arreglos: ")
print(mult_arr)
print("\n")
print("División de arreglos: ")
print(div_arr)
print("\n")
print("Exponente de arreglos: ")
print(exp_arr)


Suma: 
[107 157 207 257]


Multiplicación: 
[1400 2100 2800 3500]


División: 
[20. 30. 40. 50.]


Exponente: 
[ 1000000000000000000  1549871227580896768 -4508834063867445248
 -3778757632877184512]


Suma de arreglos: 
[1118 1118 1121]


Multiplicación de arreglos: 
[299256 312465 252904]


División de arreglos: 
[0.65875371 1.01441441 0.38737624]


Exponente de arreglos: 
[                   0 -7227082744309055221 -2561141447223591999]


In [ ]:
#5 Funciones

#Raíz cuadrada
sqrt = np.sqrt(arr)
print("Raíz cuadrada: ")
print(sqrt)
print("\n")

#Promedio
mean = np.mean(arr)
print("Media: ")
print(mean)
print("\n")

#Suma
sumx = np.sum(arr)
print("Suma: ")
print(sumx)
print("\n")

#Máximo
max = np.max(arr)
print("Máximo: ")
print(max)
print("\n")

#Mínimo
min = np.min(arr)
print("Mínimo: ")
print(min)
print("\n")

#Desviación estándar
std = np.std(arr)
print("Desviación estándar: ")
print(std)

Raíz cuadrada: 
[10.         12.24744871 14.14213562 15.8113883 ]


Media: 
175.0


Suma: 
700


Máximo: 
250


Mínimo: 
100


Desviación estándar: 
55.90169943749474
